use_frameworks!

platform :ios, '10.0'

target 'AESegmentedControl_Example' do
  pod 'AESegmentedControl', :path => '../'

  target 'AESegmentedControl_Tests' do
    inherit! :search_paths

    
  end
end
